### ISSUE TITLE
python binding fails to compile

### ISSUE THREAD

**Issue by axeldavy** [mnhrdt/iio#11]
Here is the error

piio/libraw_interface.cpp:42:17: error: « IIO_MAX_DIMENSION » n'a pas été déclaré dans cette portée
       int sizes[IIO_MAX_DIMENSION];
                 ^~~~~~~~~~~~~~~~~
piio/libraw_interface.cpp:42:17: note: alternatives suggérées: « IP_MAX_MEMBERSHIPS »
       int sizes[IIO_MAX_DIMENSION];
                 ^~~~~~~~~~~~~~~~~
                 IP_MAX_MEMBERSHIPS
piio/libraw_interface.cpp: Dans la fonction « int try_reading_file_with_libraw(const char*, iio_image*) »:
piio/libraw_interface.cpp:120:7: error: « struct iio_image » n'a pas de membre nommé « sizes »
    x->sizes[0] = S.raw_width;
       ^~~~~
piio/libraw_interface.cpp:121:7: error: « struct iio_image » n'a pas de membre nommé « sizes »
    x->sizes[1] = S.raw_height;
       ^~~~~
piio/libraw_interface.cpp: Dans la fonction « int try_reading_file_with_libraw_4channels(const char*, iio_image*) »:
piio/libraw_interface.cpp:196:7: error: « struct iio_image » n'a pas de membre nommé « sizes »
    x->sizes[0] = S.iwidth/2;
       ^~~~~
piio/libraw_interface.cpp:197:7: error: « struct iio_image » n'a pas de membre nommé « sizes »
    x->sizes[1] = S.iheight/2;

**Comment by mnhrdt** [comment]
i cannot reproduce this error

can you please post exactly what steps did you follow, and on what system?

**Comment by axeldavy** [comment]
I went to https://github.com/mnhrdt/iio/tree/master/contrib/piio_packaged
and did python setup.py install --prefix=$HOME/.local

**Comment by axeldavy** [comment]
I use archlinux. Visibly the problem is that iio.c is the only file that defines IIO_MAX_DIMENSION, but libraw_interface.cpp needs it.

**Comment by mnhrdt** [comment]
2a23bbead7a83f5f2f0e08bb8d22d02e620d7fc should fix this

**Comment by axeldavy** [comment]
Thank you for the fix !

**Comment by mnhrdt** [comment]
thank you very much for the bug report!
