### ISSUE TITLE
piio should convert array to order C

### ISSUE THREAD

**Issue by axeldavy** [mnhrdt/iio#12]
I had a weird bug with some images badly written.
I discovered what I had saved was in Fortran order,
and piio doesn't care and write as if it was C order.

Thus piio.write should convert the input arrays to C order if necessary.
I used data = np.array(data, order='C')
but it involves a copy, which is not necessary when already in C order.
I think it should work with np.asarray(data, order='C') which should convert only if needed.

If iio requires the data is continuous, numpy.ascontiguousarray converts if needed to C continuous order.

**Comment by mnhrdt** [comment]
If this solves a problem, it is OK to make several copies of the data, these functions are intended for small images.

Yet, I did not observe any artifacts with the C/python interface, can you show some code that consistently writes an images in bad order ? (I guess it will only fail for non-square images)

**Comment by axeldavy** [comment]
Here is a test:
import piio
import numpy as np
import numpy.random
data = np.random.random([6, 7, 8])
data = np.array(data, order='F')
piio.write("/tmp/tmp.tif", data)
data2 = piio.read("/tmp/tmp.tif")
assert(np.all(data == data2))

**Comment by mnhrdt** [comment]
I do not know anything about the philosophy of numpy, but I very much expect the assertion above to fail.  Doesn't the data reordering amount to a matrix transposition?  If you write and then read an array (without messing with the ordering), you always obtain consistent results.  What other requirement do you have?

That said, no need for me to understand this, if you make a PR with the desired behaviour I accept it right away :)

**Comment by gfacciol** [comment]
You can't do this:
 data = np.array(data, order='F')

**Comment by axeldavy** [comment]
of course you can do that, just try out.


If you do data2 = np.array(data, order='F') and data was order 'C'.
you should have np.all(data == data2)

The thing is that piio acts as if order was C when it writes the file.

**Comment by mnhrdt** [comment]
when you do this

b = np.array(a, order='F')

is there a way to distinguish between a and b without looking at their .data fields?

**Comment by axeldavy** [comment]
You have numpy.isfortran

https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ascontiguousarray.html
says you can look at the field a.flags['C_CONTIGUOUS']

**Comment by axeldavy** [comment]
Up

**Comment by mnhrdt** [comment]
what i said a year ago still applies:

>  If you write and then read an array (without messing with the ordering), you always obtain consistent results. What other requirement do you have?
> 
> That said, no need for me to understand this, if you make a PR with the desired behaviour I accept it right away :)

**Comment by axeldavy** [comment]
> If you write and then read an array (without messing with the ordering), you always obtain consistent results. What other requirement do you have?

No, that's the sample code I showed show that if you write your data and read it again, you get different result.
The code
`assert(np.all(data == data2))`
Doesn't care if data is stored in F or C order. F and C order just tell how is organized the data in memory, and when you ask a specific index, numpy knows where to read it properly.
Thus my example shows that since piio assumes C order, when you write data in F order, it gets writen wrong, as when you read it back, the above assert fails.

**Comment by gfacciol** [comment]
cc98664  : corrects this behavior
