### ISSUE TITLE
octave module crashes

### ISSUE THREAD

**Issue by axeldavy** [mnhrdt/iio#20]
a = iio_read('mytiff.tiff')
octave-gui: iio.c :3705 : read_image_f:  l'assertion « nbuf > 0 » a échoué.

the tiff was writen with piio.

make test also fails in the octave dir.

**Comment by mnhrdt** [comment]
can you please upload the tiff file?  It works with the ones that I try.

**Comment by mnhrdt** [comment]
> make test also fails in the octave dir.

I added a travis test for the octave build on linux

**Comment by mnhrdt** [comment]
> a = iio_read('mytiff.tiff')
> octave-gui: iio.c :3705 : read_image_f: l'assertion « nbuf > 0 » a échoué.
> 
> the tiff was writen with piio.
> 
> make test also fails in the octave dir.

is this still relevant?

**Comment by mnhrdt** [comment]
please reopen if still relevant
